### ISSUE TITLE
Error: The "url" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by nhoizey** [bertrandom/flickr-oauth-dance#1]
Trying to start a project with Node.js and Flickr API with flickr-oauth-dance, but it fails:

```
internal/validators.js:118
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:118:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at Request._callback (/Users/nhoizey/.nvm/versions/node/v13.6.0/lib/node_modules/flickr-oauth-dance/index.js:164:26)
    at Request.self.callback (/Users/nhoizey/.nvm/versions/node/v13.6.0/lib/node_modules/flickr-oauth-dance/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/Users/nhoizey/.nvm/versions/node/v13.6.0/lib/node_modules/flickr-oauth-dance/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:321:20)
    at IncomingMessage.<anonymous> (/Users/nhoizey/.nvm/versions/node/v13.6.0/lib/node_modules/flickr-oauth-dance/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:427:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by bertrandom** [comment]
Thanks for the bug report, I pushed a new version to npm (v1.0.4) that should fix this issue

**Comment by nhoizey** [comment]
Thanks! 👍
